//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class Книги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Книги()
        {
            this.Пользователь_Книга = new HashSet<Пользователь_Книга>();
            this.Отзывы = new HashSet<Отзывы>();
        }
    
        public int Код { get; set; }
        [Required]
        public int Автор { get; set; }
        [Required]
        public string Название { get; set; }
        public string Серия { get; set; }
        public string Жанр { get; set; }
        [DisplayName("Год выпуска")]
        public Nullable<int> Год_выпуска { get; set; }
        [DisplayName("Краткое описание")]
        public string Краткое_описание { get; set; }
        [DisplayName("Ссылка на скачивание")]
        public string Ссылка_на_скачивание { get; set; }
        [DisplayName("Средний рейтинг")]
        public Nullable<float> Средний_рейтинг { get; }
        public virtual Авторы Авторы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователь_Книга> Пользователь_Книга { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отзывы> Отзывы { get; set; }
    }
}
