//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь_Книга
    {
        public string Пользователь { get; set; }
        public int Код_книги { get; set; }
        public string Статус { get; set; }
        public Nullable<short> Рейтинг { get; set; }
    
        public virtual Книги Книги { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
